name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: spells-that-dont-suck.zip
        directory: "spells-that-dont-suck"
        type: zip
        name: Publish
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: spells-that-dont-suck.zip
        asset_name: spells-that-dont-suck.zip
